sentence=input("Enter the sentence:")
print("Uppercase:",sentence.upper())
print("Lowercase:",sentence.lower())
word=sentence.strip()
print("Characters:",len(word))
word1=sentence.split()
print("words:",len(word1))
print("Contains AI:","AI" in sentence)
print("First word:",word1[0])
print("Last word:",word1[-1])